# general
text: "a DSLR photo of a peacock"
log: "log/magic3d/peacock"
sd_version: "2.1"

# training parameters
device: 'cuda:1'
seed: 42
lr: 1.0e-2
weight_decay: 0.0
max_steps: 10000
log_interval: 100
eval_interval: 1000
train_dataset_size: 100
train_h: 256
train_w: 256
eval_dataset_size: 5
eval_h: 256
eval_w: 256
eval_chunk_size: 65536

# radiance field
backbone: 'ngp'
grid_resolution: 128
grid_update_interval: 10
grid_update_ema_decay: 0.6
use_predict_normal: True
use_predict_bkgd: True
density_bias_scale: 10
offset_scale: 0.5

# scene parameters
aabb: "-1.0,-1.0,-1.0,1.0,1.0,1.0"
near_plane: 0.05
far_plane: null

# render parameters
n_samples: 512  # 1024 in the paper setting
cone_angle: 0.0
alpha_thre: 0.0

# regularization
use_shading: False
start_shading_step: 1000
shading_sample_prob: "0.125,0.125,0.75"   # "albedo", "textureless", "lambertian"

use_orient_loss: False
lambda_orient: 1.0e-2
use_opacity_loss: False
lambda_opacity: 1.0e-3
use_entropy_loss: False
lambda_entropy: 1.0e-4
